### ISSUE TITLE
Membuat Struktur Tiap Node (Class Node)

### ISSUE THREAD

**Issue by galihsatriawan** [galihsatriawan/Final-Project-of-Algorithm-Design-and-Technique#2]
Dimana tiap Node memiliki :
1. Id Node 
2. Nama
3. Kumpulan Edge (kumpulan Node Tetangga, jarak)

**Comment by rhesal** [comment]
sudah bikin class tp program belum lengkap

**Comment by galihsatriawan** [comment]
- Perbaikan attribut (variable)
- tambah Getter Setter
