### ISSUE TITLE
Membuat Suatu Method untuk Insert Node

### ISSUE THREAD

**Issue by galihsatriawan** [galihsatriawan/Final-Project-of-Algorithm-Design-and-Technique#4]
Ketika Insert Node maka akan ditambahkan ke Suatu Array (Kumpulan Node) dan Dictionary

**Comment by rhesal** [comment]
Method untuk insert node telah dibuat

mohon dikoreksi bang apabila ada kekurangan

**Comment by galihsatriawan** [comment]
Cuma tinggal panggil method create_dictionary dalam method create_kumpNode mas

**Comment by galihsatriawan** [comment]
Ketika insert kump_node otomatis insert di dictionary

**Comment by galihsatriawan** [comment]
Oke mas, silahkan di close
